### PR TITLE
add the ability to edit vips using @web/vip permissions

### PR DESCRIPTION
**Pull request by Yeagorn**
- added option to edit, create and delete vips having @web/vip permissions.

Here are the following permissions needed in order to be able to delete/edit/create vips:

1. @web/vip.create - Create the vips
2. @web/vip.edit - Edit the vips
3. @web/vip.delete - Deletes the vips

### CODE REVIEW

**Comment by originalaidn** [comment]
Please don't forget to add these permissions here for new users who installing the panel:
https://github.com/counterstrikesharp-panel/css-bans/blob/7dd9bfc31e85c8e900a8443c79efd84d69245897/storage/app/cssbans.sql#L123

**Comment by Yeagorn** [comment]
> Please don't forget to add these permissions after here for new users who installing the panel:
> 
> https://github.com/counterstrikesharp-panel/css-bans/blob/7dd9bfc31e85c8e900a8443c79efd84d69245897/storage/app/cssbans.sql#L123

This one should be added as well since I forgot about it
`(NULL, '@web/vip.create', 'Web-only: Permission to create vip.', '2024-04-14 15:27:44', '2024-04-14 15:27:44'),
(NULL, '@web/vip.edit', 'Web-only: Permission to edit vip.', '2024-04-14 15:27:44', '2024-04-14 15:27:44'),
(NULL, '@web/vip.delete', 'Web-only: Permission to delete vip.', '2024-04-14 15:27:44', '2024-04-14 15:27:44');`

**Comment by hobsRKM** [comment]
> > Please don't forget to add these permissions after here for new users who installing the panel:
> > https://github.com/counterstrikesharp-panel/css-bans/blob/7dd9bfc31e85c8e900a8443c79efd84d69245897/storage/app/cssbans.sql#L123
> 
> This one should be added as well since I forgot about it `(NULL, '@web/vip.create', 'Web-only: Permission to create vip.', '2024-04-14 15:27:44', '2024-04-14 15:27:44'), (NULL, '@web/vip.edit', 'Web-only: Permission to edit vip.', '2024-04-14 15:27:44', '2024-04-14 15:27:44'), (NULL, '@web/vip.delete', 'Web-only: Permission to delete vip.', '2024-04-14 15:27:44', '2024-04-14 15:27:44');`

Add this too and commit

**Comment by Yeagorn** [comment]
Done,

@originalaidn permissions for mute.unmute was there before.

**Comment by originalaidn** [comment]
> Done,
> 
> @originalaidn permissions for mute.unmute was there before.

yep, i know it. Just to put after that, but good also what u did. thanks!

**Comment by Yeagorn** [comment]
Thanks

**Pull request merged**
